import { memo } from 'react';

const cardDefs = [
  { key: 'total', label: 'Total Registrations', icon: 'fa-users', color: 'var(--orange)' },
  { key: 'filtered', label: 'Filtered Records', icon: 'fa-filter', color: '#3b82f6' },
  { key: 'duplicates', label: 'Duplicates Removed', icon: 'fa-copy', color: '#ef4444' },
  { key: 'selected', label: 'Selected Records', icon: 'fa-check-square', color: '#22c55e' },
  { key: 'final', label: 'Final Export Count', icon: 'fa-file-export', color: '#8b5cf6' },
  { key: 'generatedBy', label: 'Generated By', icon: 'fa-user', color: '#6b7280' },
];

function ExportSummary({ totalRegistrations, filteredRecords, duplicatesRemoved, selectedRows, finalExportCount, generatedBy }) {
  const values = {
    total: totalRegistrations,
    filtered: filteredRecords,
    duplicates: duplicatesRemoved,
    selected: selectedRows,
    final: finalExportCount,
    generatedBy: generatedBy,
  };

  return (
    <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(140px, 1fr))', gap: '0.75rem' }}>
      {cardDefs.map(card => (
        <div key={card.key} style={{
          background: 'var(--card)',
          border: '1px solid var(--border)',
          borderRadius: 12,
          padding: '0.75rem',
          display: 'flex',
          flexDirection: 'column',
          gap: '0.25rem',
        }}>
          <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', color: 'var(--text-muted)', fontSize: '0.68rem' }}>
            <span>{card.label}</span>
            <i className={`fas ${card.icon}`} style={{ color: card.color, opacity: 0.6 }} />
          </div>
          <div style={{ fontSize: '1.1rem', fontWeight: 850, color: 'var(--text)' }}>
            {values[card.key]}
          </div>
        </div>
      ))}
    </div>
  );
}

export default memo(ExportSummary);
