import { normalizeDepartment } from './normalizeDepartment';

const FIXED_COLUMNS = [
  { key: 'fullName',       label: 'Full Name',        group: 'Basic Information' },
  { key: 'email',          label: 'Email Address',     group: 'Basic Information' },
  { key: 'phone',          label: 'Phone Number',      group: 'Basic Information' },
  { key: 'registerNumber', label: 'Register Number',   group: 'Academic Information' },
  { key: 'year',           label: 'Year',              group: 'Academic Information' },
  { key: 'className',      label: 'Class',             group: 'Academic Information' },
  { key: 'department',     label: 'Department',        group: 'Academic Information' },
  { key: 'id',             label: 'Registration ID',   group: 'Registration Information' },
  { key: 'status',         label: 'Status',            group: 'Registration Information' },
  { key: 'registeredAt',   label: 'Registration Date', group: 'Registration Information' },
];

const RESERVED_KEYS = FIXED_COLUMNS.map(c => c.key);

export function deduplicateById(rows) {
  const seen = new Map();
  const duplicates = [];
  const unique = [];
  rows.forEach(row => {
    if (seen.has(row.id)) {
      duplicates.push({ duplicate: row, original: seen.get(row.id) });
    } else {
      seen.set(row.id, row);
      unique.push(row);
    }
  });
  return { unique, duplicates };
}

export function getExportColumns(formFields = []) {
  return [
    ...FIXED_COLUMNS,
    ...formFields
      .filter(f => !RESERVED_KEYS.includes(f.id))
      .map(f => ({ key: f.id, label: f.label, group: 'Custom Fields' })),
  ];
}

export function extractFieldValue(reg, key) {
  const d = reg.submittedData || {};
  const map = {
    id:             () => reg.id,
    email:          () => reg.userEmail,
    registeredAt:   () => reg.registeredAt ? new Date(reg.registeredAt).toLocaleDateString() : '—',
    status:         () => reg.status,
    fullName:       () => d.fullName,
    phone:          () => d.phone,
    registerNumber: () => d.registerNumber,
    year:           () => d.year,
    className:      () => d.className,
    department:     () => normalizeDepartment(d.department),
  };
  const val = (map[key] || (() => d[key]))();
  if (val === null || val === undefined || val === '') return '—';
  if (Array.isArray(val)) return val.join(', ');
  return String(val);
}

export function sortRegistrations(rows, { field, direction }) {
  if (!field) return rows;
  const dir = direction === 'desc' ? -1 : 1;
  return [...rows].sort((a, b) => {
    let va, vb;
    const d = (r) => r.submittedData || {};
    switch (field) {
      case 'registeredAt': va = a.registeredAt || ''; vb = b.registeredAt || ''; break;
      case 'name':         va = d(a).fullName || ''; vb = d(b).fullName || ''; break;
      case 'department':   va = d(a).department || ''; vb = d(b).department || ''; break;
      case 'year':         va = d(a).year || ''; vb = d(b).year || ''; break;
      case 'status':       va = a.status || ''; vb = b.status || ''; break;
      default:             va = ''; vb = '';
    }
    return String(va).localeCompare(String(vb)) * dir;
  });
}

export function formatFilters(activeFilters) {
  if (!activeFilters) return 'None';
  const parts = [];
  if (activeFilters.statusFilter && activeFilters.statusFilter !== 'All') {
    parts.push(`Status=${activeFilters.statusFilter}`);
  }
  if (activeFilters.search) {
    parts.push(`Search="${activeFilters.search}"`);
  }
  return parts.length ? parts.join(', ') : 'None';
}

export function buildExportData(registrations, formFields, selectedKeys, sortConfig, announcement, user, activeFilters) {
  const sorted = sortRegistrations(registrations, sortConfig);
  const allCols = getExportColumns(formFields);
  const cols = allCols.filter(c => selectedKeys.has(c.key));

  const now = new Date();
  const headerRows = [
    ['MindCraft AI Club'],
    ['Velalar College of Engineering and Technology'],
    [''],
    ['Event', announcement.title || ''],
    ['Generated Date', now.toLocaleDateString()],
    ['Generated Time', now.toLocaleTimeString()],
    ['Generated By', user?.name || 'Admin'],
    ['Total Records', String(sorted.length)],
    ['Applied Filters', formatFilters(activeFilters)],
    [''],
  ];

  const colHeaders = cols.map(c => c.label);
  const dataRows = sorted.map(reg => cols.map(c => extractFieldValue(reg, c.key)));
  const footerRows = [
    [''],
    ['Generated by MindCraft AI Club Registration Management System'],
  ];

  return { headerRows, colHeaders, dataRows, footerRows };
}

function escapeCSV(val) {
  const safe = val === null || val === undefined ? '—' : String(val);
  return `"${safe.replace(/"/g, '""')}"`;
}

export function triggerCSVDownload(headerRows, colHeaders, dataRows, footerRows, filename) {
  const lines = [
    ...headerRows.map(r => r.map(escapeCSV).join(',')),
    colHeaders.map(escapeCSV).join(','),
    ...dataRows.map(row => row.map(escapeCSV).join(',')),
    ...footerRows.map(r => r.map(escapeCSV).join(',')),
  ];
  const blob = new Blob([lines.join('\n')], { type: 'text/csv;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export async function triggerXLSXDownload(headerRows, colHeaders, dataRows, footerRows, filename) {
  const XLSX = await import('xlsx');
  const allRows = [...headerRows, colHeaders, ...dataRows, ...footerRows];
  const ws = XLSX.utils.aoa_to_sheet(allRows);
  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, ws, 'Registrations');
  XLSX.writeFile(wb, filename);
}

export const PRESETS = {
  complete: {
    label: 'Complete Export',
    icon: 'fa-file-export',
    description: 'All available columns',
    getColumns: (formFields) => new Set(getExportColumns(formFields).map(c => c.key)),
  },
  attendance: {
    label: 'Attendance Sheet',
    icon: 'fa-clipboard-check',
    description: 'Name, Reg No, Year, Class, Status',
    getColumns: () => new Set(['fullName', 'registerNumber', 'year', 'className', 'status']),
  },
  certificates: {
    label: 'Certificate List',
    icon: 'fa-certificate',
    description: 'Name, Email, Department, Status',
    getColumns: () => new Set(['fullName', 'email', 'department', 'status']),
  },
  contacts: {
    label: 'Contact List',
    icon: 'fa-address-book',
    description: 'Name, Email, Phone',
    getColumns: () => new Set(['fullName', 'email', 'phone']),
  },
  custom: {
    label: 'Custom',
    icon: 'fa-sliders',
    description: 'Choose your own columns',
    getColumns: () => null,
  },
};
